name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # Replace with your branch name if different
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Updated to latest stable version

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      # Debug: List screenshots folder before uploading artifact
      - name: Debug screenshots directory
        run: ls -l .automated-rendering/screenshot-capture/screenshots/

      - name: Upload artifact
        uses: actions/upload-artifact@v4 # Updated to latest stable version
        with:
          name: github-pages
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4